DROP TABLE IF EXISTS ALARMS;

CREATE TABLE ALARMS
(
	ALARM_NAME NVARCHAR(50) NOT NULL,
	SNOOZE_TIME BIGINT NULL,
	SCHED_NAME NVARCHAR(120) NOT NULL,
	TRIGGER_NAME NVARCHAR(150) NOT NULL,
    TRIGGER_GROUP NVARCHAR(150) NOT NULL,
	PRIMARY KEY (ALARM_NAME),
	FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) ON DELETE CASCADE
);